// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV9RVseeOQllw-lcoDIVOQLmqIqZSYv5o',
    appId: '1:763476605190:web:88e6b7eecdd956158b0687',
    messagingSenderId: '763476605190',
    projectId: 'study-app-20cb2',
    authDomain: 'study-app-20cb2.firebaseapp.com',
    storageBucket: 'study-app-20cb2.appspot.com',
    measurementId: 'G-JP431JKW1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9iv9qOTGCqZQ3gVMJ1jXWErgtutg06Gs',
    appId: '1:763476605190:android:1d680d70a5f2b0128b0687',
    messagingSenderId: '763476605190',
    projectId: 'study-app-20cb2',
    storageBucket: 'study-app-20cb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOiU-EUMKp9lolDru1KzNLXanft45EaFk',
    appId: '1:763476605190:ios:60abe6d4413b86038b0687',
    messagingSenderId: '763476605190',
    projectId: 'study-app-20cb2',
    storageBucket: 'study-app-20cb2.appspot.com',
    iosClientId: '763476605190-p8i6ueuhus5b22luh16oa8ufrkbsfp8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOiU-EUMKp9lolDru1KzNLXanft45EaFk',
    appId: '1:763476605190:ios:60abe6d4413b86038b0687',
    messagingSenderId: '763476605190',
    projectId: 'study-app-20cb2',
    storageBucket: 'study-app-20cb2.appspot.com',
    iosClientId: '763476605190-p8i6ueuhus5b22luh16oa8ufrkbsfp8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
