// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvxSZl1y4Yqmq3U8UfwuVgrQW49uRRRY',
    appId: '1:410068070099:web:e448fdb81a9fdbd979ee26',
    messagingSenderId: '410068070099',
    projectId: 'flutter-study-app-2edf4',
    authDomain: 'flutter-study-app-2edf4.firebaseapp.com',
    storageBucket: 'flutter-study-app-2edf4.appspot.com',
    measurementId: 'G-NFR1V4W4D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1uT_GxbuB0nAX1OvRXJHBt4zK7JEKB-Q',
    appId: '1:410068070099:android:c1e6ac258efc4bf979ee26',
    messagingSenderId: '410068070099',
    projectId: 'flutter-study-app-2edf4',
    storageBucket: 'flutter-study-app-2edf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSxtXoZehNNFeU2mbluFAvri96tyytcQ',
    appId: '1:410068070099:ios:3c54209a36f8a9be79ee26',
    messagingSenderId: '410068070099',
    projectId: 'flutter-study-app-2edf4',
    storageBucket: 'flutter-study-app-2edf4.appspot.com',
    iosClientId: '410068070099-45jn6leb0cvonhsseb0a790lscn4027o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSxtXoZehNNFeU2mbluFAvri96tyytcQ',
    appId: '1:410068070099:ios:3c54209a36f8a9be79ee26',
    messagingSenderId: '410068070099',
    projectId: 'flutter-study-app-2edf4',
    storageBucket: 'flutter-study-app-2edf4.appspot.com',
    iosClientId: '410068070099-45jn6leb0cvonhsseb0a790lscn4027o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
